spring.application.name=Student
spring.datasource.url=jdbc:mysql://localhost:3306/students
spring.datasource.username=root
spring.datasource.password=2303031540117

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true